#!/usr/bin/bash

if [[ -z "$NNN_PIPE" ]]; then
    exit 1
fi

. "${0%/*}/.nnn-plugin-helper" 2>/dev/null

selection="${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}"
tmpdir=$(mktemp -d /tmp/nnn-${0##*/}-XXXXXXXX)
trap 'rm -rf "$tmpdir"' EXIT

printf "Filter by:\n1. Viewed only\n2. Unviewed only\n3. Cancel\n\nSelect [1-3]: "
read -r choice

case "$choice" in
    1) filter_mode="viewed" ;;
    2) filter_mode="unviewed" ;;
    *) exit 0 ;;
esac

current_dir="${PWD}"

count=0
find "$current_dir" -maxdepth 1 -type f | while read -r file; do
    has_attr=$(getfattr -n user.viewed "$file" 2>/dev/null)

    if [[ "$filter_mode" = "viewed" && -n "$has_attr" ]]; then
        ln -s "$file" "$tmpdir/${file##*/}"
        count=$((count + 1))
    elif [[ "$filter_mode" = "unviewed" && -z "$has_attr" ]]; then
        ln -s "$file" "$tmpdir/${file##*/}"
        count=$((count + 1))
    fi
done

if [ ! "$(ls -A "$tmpdir" 2>/dev/null)" ]; then
    printf "\nNo %s files found in current directory.\n" "$filter_mode"
    read -r -p "Press Enter to continue..."
    exit 0
fi

printf "1\0" > "$NNN_PIPE"
printf "cd %s\0" "$tmpdir" > "$NNN_PIPE"

printf "\nShowing %s files (temporary view)\n" "$filter_mode"
